version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    restart: unless-stopped
    ports:
      - "5460:5432"
    environment:
      POSTGRES_PASSWORD: pizza_shop
      POSTGRES_USER: pizza_shop
      POSTGRES_DB: pizza_shop
